guest = ['guilin', 'flora', 'jay', 'taylor']
message = "I would like to invite " + guest[0].title() + " to our dinner on Sat night!"
print(message)
guest[1] = 'will'
print(guest)
unattended = guest.pop(1)
print("I feel sad since " + unattended.title() + " is unable to come today")
del guest[1]
print(guest)
guest.append('david')
guest.append('jimmy')
guest.append('cj')
print(guest)
print("Dear " + guest[0].title() + ", please come to our dinner on Sat night!")
guest.insert(5, 'lily')
print(guest)
print("Hi Everyone, please welcome " +guest[5].title() + " to our party today!")
guest.append('joy')
print(guest)
print("You are welcome to our dinner today, dear " + guest[0].title() + "!")
print("You are mostly welcome to our dinner tonight, dear " + guest[1].title() +"!")
print(guest)
print("I am sorry that I can only invite two of you to our dinner as table was able to be delivered today. Dear " + guest[1].title()  + " and " + guest [2].title() + ", lucky ones!")
unlucky = guest.pop()
print(guest)
nextunlucky = guest.pop()
print(nextunlucky)
unlucky = guest.pop(2)
print(unlucky)
print(guest)
unlucky = guest.pop(1)
unlucky = guest.pop(2)
print(guest)
print("Dear bro " + guest[0].title() + " and " + guest[1].title() + ", you are still welcome to the party!")
del guest[0]
del guest[0]
print(guest)
print(len(guest))
guest.append('guilin')
guest.append('flora')
print(guest)
print("I would still like to invite " + len(guest) + " guests to our dinner tonight")
