cars = ['bmw', 'audi', 'toyota', 'subaru']
print(cars) 
len(cars)   
wanted = ['tokyo', 'la', 'ny', 'beijing', 'shanghai']
print(wanted)
print(sorted(wanted))
print(wanted)
wanted.reverse()
print(wanted)  
wanted.reverse()
print(wanted)
print(sorted(wanted,reverse=True))
print(wanted)
wanted.reverse()
print(wanted)
wanted.reverse()
print(wanted)
wanted.sort()
print(wanted)
wanted.sort(reverse=True)
print(wanted)